language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - wget http://downloads.xiph.org/releases/opus/opus-1.1.tar.gz
  - tar xzf opus-1.1.tar.gz
  - (cd opus-1.1/ && ./configure && make && sudo make install)
  - sudo apt-get install -y protobuf-c-compiler libprotobuf-c0-dev luajit libluajit-5.1-dev libvorbis-dev libssl-dev libev-dev
script: make piepan
